// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignalingSessionHold.proto

package net.igap.proto;

public final class ProtoSignalingSessionHold {
  private ProtoSignalingSessionHold() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SignalingSessionHoldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SignalingSessionHold)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    net.igap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     */
    net.igap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>bool hold = 2;</code>
     * @return The hold.
     */
    boolean getHold();
  }
  /**
   * Protobuf type {@code proto.SignalingSessionHold}
   */
  public static final class SignalingSessionHold extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SignalingSessionHold)
      SignalingSessionHoldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignalingSessionHold.newBuilder() to construct.
    private SignalingSessionHold(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignalingSessionHold() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SignalingSessionHold();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignalingSessionHold(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.igap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.igap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              hold_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHold_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHold_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.class, net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.igap.proto.ProtoRequest.Request request_;
    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    @java.lang.Override
    public net.igap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? net.igap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     */
    @java.lang.Override
    public net.igap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int HOLD_FIELD_NUMBER = 2;
    private boolean hold_;
    /**
     * <code>bool hold = 2;</code>
     * @return The hold.
     */
    @java.lang.Override
    public boolean getHold() {
      return hold_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (hold_ != false) {
        output.writeBool(2, hold_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (hold_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hold_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold)) {
        return super.equals(obj);
      }
      net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold other = (net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (getHold()
          != other.getHold()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + HOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHold());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SignalingSessionHold}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SignalingSessionHold)
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHold_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHold_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.class, net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.Builder.class);
      }

      // Construct using net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        hold_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHold_descriptor;
      }

      @java.lang.Override
      public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold getDefaultInstanceForType() {
        return net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.getDefaultInstance();
      }

      @java.lang.Override
      public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold build() {
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold buildPartial() {
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold result = new net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.hold_ = hold_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold) {
          return mergeFrom((net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold other) {
        if (other == net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getHold() != false) {
          setHold(other.getHold());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.igap.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.igap.proto.ProtoRequest.Request, net.igap.proto.ProtoRequest.Request.Builder, net.igap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       * @return The request.
       */
      public net.igap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.igap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(net.igap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          net.igap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(net.igap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              net.igap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public net.igap.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public net.igap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.igap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.igap.proto.ProtoRequest.Request, net.igap.proto.ProtoRequest.Request.Builder, net.igap.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.igap.proto.ProtoRequest.Request, net.igap.proto.ProtoRequest.Request.Builder, net.igap.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private boolean hold_ ;
      /**
       * <code>bool hold = 2;</code>
       * @return The hold.
       */
      @java.lang.Override
      public boolean getHold() {
        return hold_;
      }
      /**
       * <code>bool hold = 2;</code>
       * @param value The hold to set.
       * @return This builder for chaining.
       */
      public Builder setHold(boolean value) {
        
        hold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hold = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHold() {
        
        hold_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SignalingSessionHold)
    }

    // @@protoc_insertion_point(class_scope:proto.SignalingSessionHold)
    private static final net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold();
    }

    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignalingSessionHold>
        PARSER = new com.google.protobuf.AbstractParser<SignalingSessionHold>() {
      @java.lang.Override
      public SignalingSessionHold parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignalingSessionHold(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignalingSessionHold> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignalingSessionHold> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHold getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignalingSessionHoldResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SignalingSessionHoldResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    net.igap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     */
    net.igap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>bool hold = 2;</code>
     * @return The hold.
     */
    boolean getHold();
  }
  /**
   * Protobuf type {@code proto.SignalingSessionHoldResponse}
   */
  public static final class SignalingSessionHoldResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SignalingSessionHoldResponse)
      SignalingSessionHoldResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SignalingSessionHoldResponse.newBuilder() to construct.
    private SignalingSessionHoldResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SignalingSessionHoldResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SignalingSessionHoldResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SignalingSessionHoldResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.igap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.igap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              hold_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHoldResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHoldResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.class, net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private net.igap.proto.ProtoResponse.Response response_;
    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public net.igap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? net.igap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     */
    @java.lang.Override
    public net.igap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int HOLD_FIELD_NUMBER = 2;
    private boolean hold_;
    /**
     * <code>bool hold = 2;</code>
     * @return The hold.
     */
    @java.lang.Override
    public boolean getHold() {
      return hold_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (hold_ != false) {
        output.writeBool(2, hold_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (hold_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hold_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse)) {
        return super.equals(obj);
      }
      net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse other = (net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (getHold()
          != other.getHold()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + HOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHold());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SignalingSessionHoldResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SignalingSessionHoldResponse)
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHoldResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHoldResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.class, net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.Builder.class);
      }

      // Construct using net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        hold_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.igap.proto.ProtoSignalingSessionHold.internal_static_proto_SignalingSessionHoldResponse_descriptor;
      }

      @java.lang.Override
      public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse getDefaultInstanceForType() {
        return net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.getDefaultInstance();
      }

      @java.lang.Override
      public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse build() {
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse buildPartial() {
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse result = new net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.hold_ = hold_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse) {
          return mergeFrom((net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse other) {
        if (other == net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.getHold() != false) {
          setHold(other.getHold());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.igap.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.igap.proto.ProtoResponse.Response, net.igap.proto.ProtoResponse.Response.Builder, net.igap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       * @return The response.
       */
      public net.igap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.igap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(net.igap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          net.igap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(net.igap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              net.igap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public net.igap.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public net.igap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.igap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.igap.proto.ProtoResponse.Response, net.igap.proto.ProtoResponse.Response.Builder, net.igap.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.igap.proto.ProtoResponse.Response, net.igap.proto.ProtoResponse.Response.Builder, net.igap.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private boolean hold_ ;
      /**
       * <code>bool hold = 2;</code>
       * @return The hold.
       */
      @java.lang.Override
      public boolean getHold() {
        return hold_;
      }
      /**
       * <code>bool hold = 2;</code>
       * @param value The hold to set.
       * @return This builder for chaining.
       */
      public Builder setHold(boolean value) {
        
        hold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hold = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHold() {
        
        hold_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SignalingSessionHoldResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.SignalingSessionHoldResponse)
    private static final net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse();
    }

    public static net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignalingSessionHoldResponse>
        PARSER = new com.google.protobuf.AbstractParser<SignalingSessionHoldResponse>() {
      @java.lang.Override
      public SignalingSessionHoldResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignalingSessionHoldResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SignalingSessionHoldResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignalingSessionHoldResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.igap.proto.ProtoSignalingSessionHold.SignalingSessionHoldResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SignalingSessionHold_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SignalingSessionHold_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SignalingSessionHoldResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SignalingSessionHoldResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032SignalingSessionHold.proto\022\005proto\032\rReq" +
      "uest.proto\032\016Response.proto\"E\n\024SignalingS" +
      "essionHold\022\037\n\007request\030\001 \001(\0132\016.proto.Requ" +
      "est\022\014\n\004hold\030\002 \001(\010\"O\n\034SignalingSessionHol" +
      "dResponse\022!\n\010response\030\001 \001(\0132\017.proto.Resp" +
      "onse\022\014\n\004hold\030\002 \001(\010B+\n\016net.igap.protoB\031Pr" +
      "otoSignalingSessionHoldb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.igap.proto.ProtoRequest.getDescriptor(),
          net.igap.proto.ProtoResponse.getDescriptor(),
        });
    internal_static_proto_SignalingSessionHold_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SignalingSessionHold_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SignalingSessionHold_descriptor,
        new java.lang.String[] { "Request", "Hold", });
    internal_static_proto_SignalingSessionHoldResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SignalingSessionHoldResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SignalingSessionHoldResponse_descriptor,
        new java.lang.String[] { "Response", "Hold", });
    net.igap.proto.ProtoRequest.getDescriptor();
    net.igap.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
