// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientCountRoomHistory.proto

package com.kianiranian.proto;

public final class ProtoClientCountRoomHistory {
  private ProtoClientCountRoomHistory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientCountRoomHistoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ClientCountRoomHistory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    com.kianiranian.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     */
    com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    long getRoomId();
  }
  /**
   * Protobuf type {@code proto.ClientCountRoomHistory}
   */
  public  static final class ClientCountRoomHistory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ClientCountRoomHistory)
      ClientCountRoomHistoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientCountRoomHistory.newBuilder() to construct.
    private ClientCountRoomHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientCountRoomHistory() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientCountRoomHistory();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientCountRoomHistory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.kianiranian.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.class, com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoRequest.Request request_;
    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    public com.kianiranian.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     */
    public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    public long getRoomId() {
      return roomId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory other = (com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (getRoomId()
          != other.getRoomId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientCountRoomHistory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ClientCountRoomHistory)
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.class, com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        roomId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistory_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory build() {
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory buildPartial() {
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory result = new com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.roomId_ = roomId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory) {
          return mergeFrom((com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory other) {
        if (other == com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       * @return The request.
       */
      public com.kianiranian.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          com.kianiranian.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.kianiranian.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>uint64 room_id = 2;</code>
       * @return The roomId.
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientCountRoomHistory)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientCountRoomHistory)
    private static final com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory();
    }

    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientCountRoomHistory>
        PARSER = new com.google.protobuf.AbstractParser<ClientCountRoomHistory>() {
      @java.lang.Override
      public ClientCountRoomHistory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientCountRoomHistory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientCountRoomHistory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientCountRoomHistory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientCountRoomHistoryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ClientCountRoomHistoryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    com.kianiranian.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     */
    com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>uint32 media = 2;</code>
     * @return The media.
     */
    int getMedia();

    /**
     * <code>uint32 image = 3;</code>
     * @return The image.
     */
    int getImage();

    /**
     * <code>uint32 video = 4;</code>
     * @return The video.
     */
    int getVideo();

    /**
     * <code>uint32 audio = 5;</code>
     * @return The audio.
     */
    int getAudio();

    /**
     * <code>uint32 voice = 6;</code>
     * @return The voice.
     */
    int getVoice();

    /**
     * <code>uint32 gif = 7;</code>
     * @return The gif.
     */
    int getGif();

    /**
     * <code>uint32 file = 8;</code>
     * @return The file.
     */
    int getFile();

    /**
     * <code>uint32 url = 9;</code>
     * @return The url.
     */
    int getUrl();
  }
  /**
   * Protobuf type {@code proto.ClientCountRoomHistoryResponse}
   */
  public  static final class ClientCountRoomHistoryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ClientCountRoomHistoryResponse)
      ClientCountRoomHistoryResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientCountRoomHistoryResponse.newBuilder() to construct.
    private ClientCountRoomHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientCountRoomHistoryResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientCountRoomHistoryResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientCountRoomHistoryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.kianiranian.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              media_ = input.readUInt32();
              break;
            }
            case 24: {

              image_ = input.readUInt32();
              break;
            }
            case 32: {

              video_ = input.readUInt32();
              break;
            }
            case 40: {

              audio_ = input.readUInt32();
              break;
            }
            case 48: {

              voice_ = input.readUInt32();
              break;
            }
            case 56: {

              gif_ = input.readUInt32();
              break;
            }
            case 64: {

              file_ = input.readUInt32();
              break;
            }
            case 72: {

              url_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.class, com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoResponse.Response response_;
    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    public com.kianiranian.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     */
    public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int MEDIA_FIELD_NUMBER = 2;
    private int media_;
    /**
     * <code>uint32 media = 2;</code>
     * @return The media.
     */
    public int getMedia() {
      return media_;
    }

    public static final int IMAGE_FIELD_NUMBER = 3;
    private int image_;
    /**
     * <code>uint32 image = 3;</code>
     * @return The image.
     */
    public int getImage() {
      return image_;
    }

    public static final int VIDEO_FIELD_NUMBER = 4;
    private int video_;
    /**
     * <code>uint32 video = 4;</code>
     * @return The video.
     */
    public int getVideo() {
      return video_;
    }

    public static final int AUDIO_FIELD_NUMBER = 5;
    private int audio_;
    /**
     * <code>uint32 audio = 5;</code>
     * @return The audio.
     */
    public int getAudio() {
      return audio_;
    }

    public static final int VOICE_FIELD_NUMBER = 6;
    private int voice_;
    /**
     * <code>uint32 voice = 6;</code>
     * @return The voice.
     */
    public int getVoice() {
      return voice_;
    }

    public static final int GIF_FIELD_NUMBER = 7;
    private int gif_;
    /**
     * <code>uint32 gif = 7;</code>
     * @return The gif.
     */
    public int getGif() {
      return gif_;
    }

    public static final int FILE_FIELD_NUMBER = 8;
    private int file_;
    /**
     * <code>uint32 file = 8;</code>
     * @return The file.
     */
    public int getFile() {
      return file_;
    }

    public static final int URL_FIELD_NUMBER = 9;
    private int url_;
    /**
     * <code>uint32 url = 9;</code>
     * @return The url.
     */
    public int getUrl() {
      return url_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (media_ != 0) {
        output.writeUInt32(2, media_);
      }
      if (image_ != 0) {
        output.writeUInt32(3, image_);
      }
      if (video_ != 0) {
        output.writeUInt32(4, video_);
      }
      if (audio_ != 0) {
        output.writeUInt32(5, audio_);
      }
      if (voice_ != 0) {
        output.writeUInt32(6, voice_);
      }
      if (gif_ != 0) {
        output.writeUInt32(7, gif_);
      }
      if (file_ != 0) {
        output.writeUInt32(8, file_);
      }
      if (url_ != 0) {
        output.writeUInt32(9, url_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (media_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, media_);
      }
      if (image_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, image_);
      }
      if (video_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, video_);
      }
      if (audio_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, audio_);
      }
      if (voice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, voice_);
      }
      if (gif_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, gif_);
      }
      if (file_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, file_);
      }
      if (url_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, url_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse other = (com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (getMedia()
          != other.getMedia()) return false;
      if (getImage()
          != other.getImage()) return false;
      if (getVideo()
          != other.getVideo()) return false;
      if (getAudio()
          != other.getAudio()) return false;
      if (getVoice()
          != other.getVoice()) return false;
      if (getGif()
          != other.getGif()) return false;
      if (getFile()
          != other.getFile()) return false;
      if (getUrl()
          != other.getUrl()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + MEDIA_FIELD_NUMBER;
      hash = (53 * hash) + getMedia();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage();
      hash = (37 * hash) + VIDEO_FIELD_NUMBER;
      hash = (53 * hash) + getVideo();
      hash = (37 * hash) + AUDIO_FIELD_NUMBER;
      hash = (53 * hash) + getAudio();
      hash = (37 * hash) + VOICE_FIELD_NUMBER;
      hash = (53 * hash) + getVoice();
      hash = (37 * hash) + GIF_FIELD_NUMBER;
      hash = (53 * hash) + getGif();
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFile();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientCountRoomHistoryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ClientCountRoomHistoryResponse)
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistoryResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistoryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.class, com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        media_ = 0;

        image_ = 0;

        video_ = 0;

        audio_ = 0;

        voice_ = 0;

        gif_ = 0;

        file_ = 0;

        url_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.internal_static_proto_ClientCountRoomHistoryResponse_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse build() {
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse buildPartial() {
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse result = new com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.media_ = media_;
        result.image_ = image_;
        result.video_ = video_;
        result.audio_ = audio_;
        result.voice_ = voice_;
        result.gif_ = gif_;
        result.file_ = file_;
        result.url_ = url_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse) {
          return mergeFrom((com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse other) {
        if (other == com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.getMedia() != 0) {
          setMedia(other.getMedia());
        }
        if (other.getImage() != 0) {
          setImage(other.getImage());
        }
        if (other.getVideo() != 0) {
          setVideo(other.getVideo());
        }
        if (other.getAudio() != 0) {
          setAudio(other.getAudio());
        }
        if (other.getVoice() != 0) {
          setVoice(other.getVoice());
        }
        if (other.getGif() != 0) {
          setGif(other.getGif());
        }
        if (other.getFile() != 0) {
          setFile(other.getFile());
        }
        if (other.getUrl() != 0) {
          setUrl(other.getUrl());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       * @return The response.
       */
      public com.kianiranian.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          com.kianiranian.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              com.kianiranian.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private int media_ ;
      /**
       * <code>uint32 media = 2;</code>
       * @return The media.
       */
      public int getMedia() {
        return media_;
      }
      /**
       * <code>uint32 media = 2;</code>
       * @param value The media to set.
       * @return This builder for chaining.
       */
      public Builder setMedia(int value) {
        
        media_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 media = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMedia() {
        
        media_ = 0;
        onChanged();
        return this;
      }

      private int image_ ;
      /**
       * <code>uint32 image = 3;</code>
       * @return The image.
       */
      public int getImage() {
        return image_;
      }
      /**
       * <code>uint32 image = 3;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(int value) {
        
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 image = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        
        image_ = 0;
        onChanged();
        return this;
      }

      private int video_ ;
      /**
       * <code>uint32 video = 4;</code>
       * @return The video.
       */
      public int getVideo() {
        return video_;
      }
      /**
       * <code>uint32 video = 4;</code>
       * @param value The video to set.
       * @return This builder for chaining.
       */
      public Builder setVideo(int value) {
        
        video_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 video = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideo() {
        
        video_ = 0;
        onChanged();
        return this;
      }

      private int audio_ ;
      /**
       * <code>uint32 audio = 5;</code>
       * @return The audio.
       */
      public int getAudio() {
        return audio_;
      }
      /**
       * <code>uint32 audio = 5;</code>
       * @param value The audio to set.
       * @return This builder for chaining.
       */
      public Builder setAudio(int value) {
        
        audio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 audio = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAudio() {
        
        audio_ = 0;
        onChanged();
        return this;
      }

      private int voice_ ;
      /**
       * <code>uint32 voice = 6;</code>
       * @return The voice.
       */
      public int getVoice() {
        return voice_;
      }
      /**
       * <code>uint32 voice = 6;</code>
       * @param value The voice to set.
       * @return This builder for chaining.
       */
      public Builder setVoice(int value) {
        
        voice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 voice = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoice() {
        
        voice_ = 0;
        onChanged();
        return this;
      }

      private int gif_ ;
      /**
       * <code>uint32 gif = 7;</code>
       * @return The gif.
       */
      public int getGif() {
        return gif_;
      }
      /**
       * <code>uint32 gif = 7;</code>
       * @param value The gif to set.
       * @return This builder for chaining.
       */
      public Builder setGif(int value) {
        
        gif_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 gif = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGif() {
        
        gif_ = 0;
        onChanged();
        return this;
      }

      private int file_ ;
      /**
       * <code>uint32 file = 8;</code>
       * @return The file.
       */
      public int getFile() {
        return file_;
      }
      /**
       * <code>uint32 file = 8;</code>
       * @param value The file to set.
       * @return This builder for chaining.
       */
      public Builder setFile(int value) {
        
        file_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 file = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFile() {
        
        file_ = 0;
        onChanged();
        return this;
      }

      private int url_ ;
      /**
       * <code>uint32 url = 9;</code>
       * @return The url.
       */
      public int getUrl() {
        return url_;
      }
      /**
       * <code>uint32 url = 9;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(int value) {
        
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 url = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientCountRoomHistoryResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientCountRoomHistoryResponse)
    private static final com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse();
    }

    public static com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientCountRoomHistoryResponse>
        PARSER = new com.google.protobuf.AbstractParser<ClientCountRoomHistoryResponse>() {
      @java.lang.Override
      public ClientCountRoomHistoryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientCountRoomHistoryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientCountRoomHistoryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientCountRoomHistoryResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoClientCountRoomHistory.ClientCountRoomHistoryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientCountRoomHistory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientCountRoomHistory_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientCountRoomHistoryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientCountRoomHistoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ClientCountRoomHistory.proto\022\005proto\032\rR" +
      "equest.proto\032\016Response.proto\"J\n\026ClientCo" +
      "untRoomHistory\022\037\n\007request\030\001 \001(\0132\016.proto." +
      "Request\022\017\n\007room_id\030\002 \001(\004\"\266\001\n\036ClientCount" +
      "RoomHistoryResponse\022!\n\010response\030\001 \001(\0132\017." +
      "proto.Response\022\r\n\005media\030\002 \001(\r\022\r\n\005image\030\003" +
      " \001(\r\022\r\n\005video\030\004 \001(\r\022\r\n\005audio\030\005 \001(\r\022\r\n\005vo" +
      "ice\030\006 \001(\r\022\013\n\003gif\030\007 \001(\r\022\014\n\004file\030\010 \001(\r\022\013\n\003" +
      "url\030\t \001(\rB4\n\025com.kianiranian.protoB\033Prot" +
      "oClientCountRoomHistoryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kianiranian.proto.ProtoRequest.getDescriptor(),
          com.kianiranian.proto.ProtoResponse.getDescriptor(),
        });
    internal_static_proto_ClientCountRoomHistory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ClientCountRoomHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientCountRoomHistory_descriptor,
        new java.lang.String[] { "Request", "RoomId", });
    internal_static_proto_ClientCountRoomHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ClientCountRoomHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientCountRoomHistoryResponse_descriptor,
        new java.lang.String[] { "Response", "Media", "Image", "Video", "Audio", "Voice", "Gif", "File", "Url", });
    com.kianiranian.proto.ProtoRequest.getDescriptor();
    com.kianiranian.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
