// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTwoStepVerificationChangeHint.proto

package com.kianiranian.proto;

public final class ProtoUserTwoStepVerificationChangeHint {
  private ProtoUserTwoStepVerificationChangeHint() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserTwoStepVerificationChangeHintOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserTwoStepVerificationChangeHint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    com.kianiranian.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     */
    com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string hint = 3;</code>
     * @return The hint.
     */
    java.lang.String getHint();
    /**
     * <code>string hint = 3;</code>
     * @return The bytes for hint.
     */
    com.google.protobuf.ByteString
        getHintBytes();
  }
  /**
   * Protobuf type {@code proto.UserTwoStepVerificationChangeHint}
   */
  public  static final class UserTwoStepVerificationChangeHint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserTwoStepVerificationChangeHint)
      UserTwoStepVerificationChangeHintOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserTwoStepVerificationChangeHint.newBuilder() to construct.
    private UserTwoStepVerificationChangeHint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserTwoStepVerificationChangeHint() {
      password_ = "";
      hint_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserTwoStepVerificationChangeHint();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserTwoStepVerificationChangeHint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.kianiranian.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              hint_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.class, com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoRequest.Request request_;
    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    public com.kianiranian.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     */
    public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HINT_FIELD_NUMBER = 3;
    private volatile java.lang.Object hint_;
    /**
     * <code>string hint = 3;</code>
     * @return The hint.
     */
    public java.lang.String getHint() {
      java.lang.Object ref = hint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hint_ = s;
        return s;
      }
    }
    /**
     * <code>string hint = 3;</code>
     * @return The bytes for hint.
     */
    public com.google.protobuf.ByteString
        getHintBytes() {
      java.lang.Object ref = hint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (!getHintBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hint_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (!getHintBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hint_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint other = (com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getHint()
          .equals(other.getHint())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + HINT_FIELD_NUMBER;
      hash = (53 * hash) + getHint().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserTwoStepVerificationChangeHint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserTwoStepVerificationChangeHint)
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.class, com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        password_ = "";

        hint_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHint_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint build() {
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint buildPartial() {
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint result = new com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.password_ = password_;
        result.hint_ = hint_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint) {
          return mergeFrom((com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint other) {
        if (other == com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getHint().isEmpty()) {
          hint_ = other.hint_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       * @return The request.
       */
      public com.kianiranian.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          com.kianiranian.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.kianiranian.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hint_ = "";
      /**
       * <code>string hint = 3;</code>
       * @return The hint.
       */
      public java.lang.String getHint() {
        java.lang.Object ref = hint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hint = 3;</code>
       * @return The bytes for hint.
       */
      public com.google.protobuf.ByteString
          getHintBytes() {
        java.lang.Object ref = hint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hint = 3;</code>
       * @param value The hint to set.
       * @return This builder for chaining.
       */
      public Builder setHint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hint = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHint() {
        
        hint_ = getDefaultInstance().getHint();
        onChanged();
        return this;
      }
      /**
       * <code>string hint = 3;</code>
       * @param value The bytes for hint to set.
       * @return This builder for chaining.
       */
      public Builder setHintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hint_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.UserTwoStepVerificationChangeHint)
    }

    // @@protoc_insertion_point(class_scope:proto.UserTwoStepVerificationChangeHint)
    private static final com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint();
    }

    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserTwoStepVerificationChangeHint>
        PARSER = new com.google.protobuf.AbstractParser<UserTwoStepVerificationChangeHint>() {
      @java.lang.Override
      public UserTwoStepVerificationChangeHint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserTwoStepVerificationChangeHint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserTwoStepVerificationChangeHint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserTwoStepVerificationChangeHint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserTwoStepVerificationChangeHintResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserTwoStepVerificationChangeHintResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    com.kianiranian.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     */
    com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code proto.UserTwoStepVerificationChangeHintResponse}
   */
  public  static final class UserTwoStepVerificationChangeHintResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserTwoStepVerificationChangeHintResponse)
      UserTwoStepVerificationChangeHintResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserTwoStepVerificationChangeHintResponse.newBuilder() to construct.
    private UserTwoStepVerificationChangeHintResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserTwoStepVerificationChangeHintResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserTwoStepVerificationChangeHintResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserTwoStepVerificationChangeHintResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.kianiranian.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHintResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHintResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.class, com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoResponse.Response response_;
    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    public com.kianiranian.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     */
    public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse other = (com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserTwoStepVerificationChangeHintResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserTwoStepVerificationChangeHintResponse)
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHintResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHintResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.class, com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.internal_static_proto_UserTwoStepVerificationChangeHintResponse_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse build() {
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse buildPartial() {
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse result = new com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse) {
          return mergeFrom((com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse other) {
        if (other == com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       * @return The response.
       */
      public com.kianiranian.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          com.kianiranian.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              com.kianiranian.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.UserTwoStepVerificationChangeHintResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.UserTwoStepVerificationChangeHintResponse)
    private static final com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse();
    }

    public static com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserTwoStepVerificationChangeHintResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserTwoStepVerificationChangeHintResponse>() {
      @java.lang.Override
      public UserTwoStepVerificationChangeHintResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserTwoStepVerificationChangeHintResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserTwoStepVerificationChangeHintResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserTwoStepVerificationChangeHintResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoUserTwoStepVerificationChangeHint.UserTwoStepVerificationChangeHintResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserTwoStepVerificationChangeHint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserTwoStepVerificationChangeHint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserTwoStepVerificationChangeHintResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserTwoStepVerificationChangeHintResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'UserTwoStepVerificationChangeHint.prot" +
      "o\022\005proto\032\rRequest.proto\032\016Response.proto\"" +
      "d\n!UserTwoStepVerificationChangeHint\022\037\n\007" +
      "request\030\001 \001(\0132\016.proto.Request\022\020\n\010passwor" +
      "d\030\002 \001(\t\022\014\n\004hint\030\003 \001(\t\"N\n)UserTwoStepVeri" +
      "ficationChangeHintResponse\022!\n\010response\030\001" +
      " \001(\0132\017.proto.ResponseB?\n\025com.kianiranian" +
      ".protoB&ProtoUserTwoStepVerificationChan" +
      "geHintb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kianiranian.proto.ProtoRequest.getDescriptor(),
          com.kianiranian.proto.ProtoResponse.getDescriptor(),
        });
    internal_static_proto_UserTwoStepVerificationChangeHint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserTwoStepVerificationChangeHint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserTwoStepVerificationChangeHint_descriptor,
        new java.lang.String[] { "Request", "Password", "Hint", });
    internal_static_proto_UserTwoStepVerificationChangeHintResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_UserTwoStepVerificationChangeHintResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserTwoStepVerificationChangeHintResponse_descriptor,
        new java.lang.String[] { "Response", });
    com.kianiranian.proto.ProtoRequest.getDescriptor();
    com.kianiranian.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
