// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MplGetBillToken.proto

package com.kianiranian.proto;

public final class ProtoMplGetBillToken {
  private ProtoMplGetBillToken() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MplGetBillTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MplGetBillToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    com.kianiranian.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     */
    com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>uint64 bill_id = 2;</code>
     * @return The billId.
     */
    long getBillId();

    /**
     * <code>uint64 pay_id = 3;</code>
     * @return The payId.
     */
    long getPayId();
  }
  /**
   * Protobuf type {@code proto.MplGetBillToken}
   */
  public  static final class MplGetBillToken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MplGetBillToken)
      MplGetBillTokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MplGetBillToken.newBuilder() to construct.
    private MplGetBillToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MplGetBillToken() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MplGetBillToken();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MplGetBillToken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.kianiranian.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              billId_ = input.readUInt64();
              break;
            }
            case 24: {

              payId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.class, com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoRequest.Request request_;
    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    public com.kianiranian.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     */
    public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int BILL_ID_FIELD_NUMBER = 2;
    private long billId_;
    /**
     * <code>uint64 bill_id = 2;</code>
     * @return The billId.
     */
    public long getBillId() {
      return billId_;
    }

    public static final int PAY_ID_FIELD_NUMBER = 3;
    private long payId_;
    /**
     * <code>uint64 pay_id = 3;</code>
     * @return The payId.
     */
    public long getPayId() {
      return payId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (billId_ != 0L) {
        output.writeUInt64(2, billId_);
      }
      if (payId_ != 0L) {
        output.writeUInt64(3, payId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (billId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, billId_);
      }
      if (payId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, payId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken other = (com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (getBillId()
          != other.getBillId()) return false;
      if (getPayId()
          != other.getPayId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + BILL_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBillId());
      hash = (37 * hash) + PAY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPayId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MplGetBillToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MplGetBillToken)
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillToken_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.class, com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        billId_ = 0L;

        payId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillToken_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken build() {
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken buildPartial() {
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken result = new com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.billId_ = billId_;
        result.payId_ = payId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken) {
          return mergeFrom((com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken other) {
        if (other == com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getBillId() != 0L) {
          setBillId(other.getBillId());
        }
        if (other.getPayId() != 0L) {
          setPayId(other.getPayId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       * @return The request.
       */
      public com.kianiranian.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          com.kianiranian.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.kianiranian.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long billId_ ;
      /**
       * <code>uint64 bill_id = 2;</code>
       * @return The billId.
       */
      public long getBillId() {
        return billId_;
      }
      /**
       * <code>uint64 bill_id = 2;</code>
       * @param value The billId to set.
       * @return This builder for chaining.
       */
      public Builder setBillId(long value) {
        
        billId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 bill_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBillId() {
        
        billId_ = 0L;
        onChanged();
        return this;
      }

      private long payId_ ;
      /**
       * <code>uint64 pay_id = 3;</code>
       * @return The payId.
       */
      public long getPayId() {
        return payId_;
      }
      /**
       * <code>uint64 pay_id = 3;</code>
       * @param value The payId to set.
       * @return This builder for chaining.
       */
      public Builder setPayId(long value) {
        
        payId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 pay_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayId() {
        
        payId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MplGetBillToken)
    }

    // @@protoc_insertion_point(class_scope:proto.MplGetBillToken)
    private static final com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken();
    }

    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MplGetBillToken>
        PARSER = new com.google.protobuf.AbstractParser<MplGetBillToken>() {
      @java.lang.Override
      public MplGetBillToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MplGetBillToken(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MplGetBillToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MplGetBillToken> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MplGetBillTokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MplGetBillTokenResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    com.kianiranian.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     */
    com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>uint32 status = 2;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>uint32 expire_time = 4;</code>
     * @return The expireTime.
     */
    int getExpireTime();

    /**
     * <code>string message = 5;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 5;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code proto.MplGetBillTokenResponse}
   */
  public  static final class MplGetBillTokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MplGetBillTokenResponse)
      MplGetBillTokenResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MplGetBillTokenResponse.newBuilder() to construct.
    private MplGetBillTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MplGetBillTokenResponse() {
      token_ = "";
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MplGetBillTokenResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MplGetBillTokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.kianiranian.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              status_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 32: {

              expireTime_ = input.readUInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillTokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.class, com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoResponse.Response response_;
    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    public com.kianiranian.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     */
    public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>uint32 status = 2;</code>
     * @return The status.
     */
    public int getStatus() {
      return status_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRE_TIME_FIELD_NUMBER = 4;
    private int expireTime_;
    /**
     * <code>uint32 expire_time = 4;</code>
     * @return The expireTime.
     */
    public int getExpireTime() {
      return expireTime_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 5;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 5;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (status_ != 0) {
        output.writeUInt32(2, status_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (expireTime_ != 0) {
        output.writeUInt32(4, expireTime_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, status_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (expireTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, expireTime_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse other = (com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (getStatus()
          != other.getStatus()) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (getExpireTime()
          != other.getExpireTime()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + EXPIRE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getExpireTime();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MplGetBillTokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MplGetBillTokenResponse)
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillTokenResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillTokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.class, com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        status_ = 0;

        token_ = "";

        expireTime_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoMplGetBillToken.internal_static_proto_MplGetBillTokenResponse_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse build() {
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse buildPartial() {
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse result = new com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.status_ = status_;
        result.token_ = token_;
        result.expireTime_ = expireTime_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse) {
          return mergeFrom((com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse other) {
        if (other == com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getExpireTime() != 0) {
          setExpireTime(other.getExpireTime());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       * @return The response.
       */
      public com.kianiranian.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          com.kianiranian.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              com.kianiranian.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private int status_ ;
      /**
       * <code>uint32 status = 2;</code>
       * @return The status.
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>uint32 status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 3;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int expireTime_ ;
      /**
       * <code>uint32 expire_time = 4;</code>
       * @return The expireTime.
       */
      public int getExpireTime() {
        return expireTime_;
      }
      /**
       * <code>uint32 expire_time = 4;</code>
       * @param value The expireTime to set.
       * @return This builder for chaining.
       */
      public Builder setExpireTime(int value) {
        
        expireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 expire_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpireTime() {
        
        expireTime_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 5;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 5;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 5;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 5;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MplGetBillTokenResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.MplGetBillTokenResponse)
    private static final com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse();
    }

    public static com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MplGetBillTokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<MplGetBillTokenResponse>() {
      @java.lang.Override
      public MplGetBillTokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MplGetBillTokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MplGetBillTokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MplGetBillTokenResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoMplGetBillToken.MplGetBillTokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MplGetBillToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MplGetBillToken_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MplGetBillTokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MplGetBillTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MplGetBillToken.proto\022\005proto\032\rRequest." +
      "proto\032\016Response.proto\"S\n\017MplGetBillToken" +
      "\022\037\n\007request\030\001 \001(\0132\016.proto.Request\022\017\n\007bil" +
      "l_id\030\002 \001(\004\022\016\n\006pay_id\030\003 \001(\004\"\201\001\n\027MplGetBil" +
      "lTokenResponse\022!\n\010response\030\001 \001(\0132\017.proto" +
      ".Response\022\016\n\006status\030\002 \001(\r\022\r\n\005token\030\003 \001(\t" +
      "\022\023\n\013expire_time\030\004 \001(\r\022\017\n\007message\030\005 \001(\tB-" +
      "\n\025com.kianiranian.protoB\024ProtoMplGetBill" +
      "Tokenb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kianiranian.proto.ProtoRequest.getDescriptor(),
          com.kianiranian.proto.ProtoResponse.getDescriptor(),
        });
    internal_static_proto_MplGetBillToken_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MplGetBillToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MplGetBillToken_descriptor,
        new java.lang.String[] { "Request", "BillId", "PayId", });
    internal_static_proto_MplGetBillTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MplGetBillTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MplGetBillTokenResponse_descriptor,
        new java.lang.String[] { "Response", "Status", "Token", "ExpireTime", "Message", });
    com.kianiranian.proto.ProtoRequest.getDescriptor();
    com.kianiranian.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
