// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatUpdateStatus.proto

package com.kianiranian.proto;

public final class ProtoChatUpdateStatus {
  private ProtoChatUpdateStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatUpdateStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ChatUpdateStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    com.kianiranian.proto.ProtoRequest.Request getRequest();
    /**
     * <code>.proto.Request request = 1;</code>
     */
    com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    long getRoomId();

    /**
     * <code>uint64 message_id = 3;</code>
     * @return The messageId.
     */
    long getMessageId();

    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The status.
     */
    com.kianiranian.proto.ProtoGlobal.RoomMessageStatus getStatus();
  }
  /**
   * Protobuf type {@code proto.ChatUpdateStatus}
   */
  public  static final class ChatUpdateStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ChatUpdateStatus)
      ChatUpdateStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatUpdateStatus.newBuilder() to construct.
    private ChatUpdateStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatUpdateStatus() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatUpdateStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatUpdateStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.kianiranian.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            case 24: {

              messageId_ = input.readUInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.class, com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoRequest.Request request_;
    /**
     * <code>.proto.Request request = 1;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     * @return The request.
     */
    public com.kianiranian.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>.proto.Request request = 1;</code>
     */
    public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    public long getRoomId() {
      return roomId_;
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 3;
    private long messageId_;
    /**
     * <code>uint64 message_id = 3;</code>
     * @return The messageId.
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The status.
     */
    public com.kianiranian.proto.ProtoGlobal.RoomMessageStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.kianiranian.proto.ProtoGlobal.RoomMessageStatus result = com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.valueOf(status_);
      return result == null ? com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      if (messageId_ != 0L) {
        output.writeUInt64(3, messageId_);
      }
      if (status_ != com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.FAILED.getNumber()) {
        output.writeEnum(4, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, messageId_);
      }
      if (status_ != com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus other = (com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus) obj;

      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (getRoomId()
          != other.getRoomId()) return false;
      if (getMessageId()
          != other.getMessageId()) return false;
      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChatUpdateStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ChatUpdateStatus)
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.class, com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        roomId_ = 0L;

        messageId_ = 0L;

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatus_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus build() {
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus buildPartial() {
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus result = new com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.roomId_ = roomId_;
        result.messageId_ = messageId_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus) {
          return mergeFrom((com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus other) {
        if (other == com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoRequest.Request request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.proto.Request request = 1;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       * @return The request.
       */
      public com.kianiranian.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder setRequest(
          com.kianiranian.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder mergeRequest(com.kianiranian.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              com.kianiranian.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.Request.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      public com.kianiranian.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.kianiranian.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoRequest.Request, com.kianiranian.proto.ProtoRequest.Request.Builder, com.kianiranian.proto.ProtoRequest.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>uint64 room_id = 2;</code>
       * @return The roomId.
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private long messageId_ ;
      /**
       * <code>uint64 message_id = 3;</code>
       * @return The messageId.
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>uint64 message_id = 3;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 message_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @return The enum numeric value on the wire for status.
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @return The status.
       */
      public com.kianiranian.proto.ProtoGlobal.RoomMessageStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.kianiranian.proto.ProtoGlobal.RoomMessageStatus result = com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.valueOf(status_);
        return result == null ? com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.kianiranian.proto.ProtoGlobal.RoomMessageStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ChatUpdateStatus)
    }

    // @@protoc_insertion_point(class_scope:proto.ChatUpdateStatus)
    private static final com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus();
    }

    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatUpdateStatus>
        PARSER = new com.google.protobuf.AbstractParser<ChatUpdateStatus>() {
      @java.lang.Override
      public ChatUpdateStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatUpdateStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatUpdateStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatUpdateStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatUpdateStatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ChatUpdateStatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    com.kianiranian.proto.ProtoResponse.Response getResponse();
    /**
     * <code>.proto.Response response = 1;</code>
     */
    com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    long getRoomId();

    /**
     * <code>uint64 message_id = 3;</code>
     * @return The messageId.
     */
    long getMessageId();

    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The status.
     */
    com.kianiranian.proto.ProtoGlobal.RoomMessageStatus getStatus();

    /**
     * <code>uint64 status_version = 5;</code>
     * @return The statusVersion.
     */
    long getStatusVersion();

    /**
     * <code>string updater_author_hash = 6;</code>
     * @return The updaterAuthorHash.
     */
    java.lang.String getUpdaterAuthorHash();
    /**
     * <code>string updater_author_hash = 6;</code>
     * @return The bytes for updaterAuthorHash.
     */
    com.google.protobuf.ByteString
        getUpdaterAuthorHashBytes();
  }
  /**
   * Protobuf type {@code proto.ChatUpdateStatusResponse}
   */
  public  static final class ChatUpdateStatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ChatUpdateStatusResponse)
      ChatUpdateStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatUpdateStatusResponse.newBuilder() to construct.
    private ChatUpdateStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatUpdateStatusResponse() {
      status_ = 0;
      updaterAuthorHash_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatUpdateStatusResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatUpdateStatusResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kianiranian.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.kianiranian.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
            case 24: {

              messageId_ = input.readUInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 40: {

              statusVersion_ = input.readUInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              updaterAuthorHash_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.class, com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.kianiranian.proto.ProtoResponse.Response response_;
    /**
     * <code>.proto.Response response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     * @return The response.
     */
    public com.kianiranian.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>.proto.Response response = 1;</code>
     */
    public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>uint64 room_id = 2;</code>
     * @return The roomId.
     */
    public long getRoomId() {
      return roomId_;
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 3;
    private long messageId_;
    /**
     * <code>uint64 message_id = 3;</code>
     * @return The messageId.
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.proto.RoomMessageStatus status = 4;</code>
     * @return The status.
     */
    public com.kianiranian.proto.ProtoGlobal.RoomMessageStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.kianiranian.proto.ProtoGlobal.RoomMessageStatus result = com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.valueOf(status_);
      return result == null ? com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.UNRECOGNIZED : result;
    }

    public static final int STATUS_VERSION_FIELD_NUMBER = 5;
    private long statusVersion_;
    /**
     * <code>uint64 status_version = 5;</code>
     * @return The statusVersion.
     */
    public long getStatusVersion() {
      return statusVersion_;
    }

    public static final int UPDATER_AUTHOR_HASH_FIELD_NUMBER = 6;
    private volatile java.lang.Object updaterAuthorHash_;
    /**
     * <code>string updater_author_hash = 6;</code>
     * @return The updaterAuthorHash.
     */
    public java.lang.String getUpdaterAuthorHash() {
      java.lang.Object ref = updaterAuthorHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updaterAuthorHash_ = s;
        return s;
      }
    }
    /**
     * <code>string updater_author_hash = 6;</code>
     * @return The bytes for updaterAuthorHash.
     */
    public com.google.protobuf.ByteString
        getUpdaterAuthorHashBytes() {
      java.lang.Object ref = updaterAuthorHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updaterAuthorHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
      if (messageId_ != 0L) {
        output.writeUInt64(3, messageId_);
      }
      if (status_ != com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.FAILED.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (statusVersion_ != 0L) {
        output.writeUInt64(5, statusVersion_);
      }
      if (!getUpdaterAuthorHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, updaterAuthorHash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, roomId_);
      }
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, messageId_);
      }
      if (status_ != com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (statusVersion_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, statusVersion_);
      }
      if (!getUpdaterAuthorHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, updaterAuthorHash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse)) {
        return super.equals(obj);
      }
      com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse other = (com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (getRoomId()
          != other.getRoomId()) return false;
      if (getMessageId()
          != other.getMessageId()) return false;
      if (status_ != other.status_) return false;
      if (getStatusVersion()
          != other.getStatusVersion()) return false;
      if (!getUpdaterAuthorHash()
          .equals(other.getUpdaterAuthorHash())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + STATUS_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatusVersion());
      hash = (37 * hash) + UPDATER_AUTHOR_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getUpdaterAuthorHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChatUpdateStatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ChatUpdateStatusResponse)
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.class, com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.Builder.class);
      }

      // Construct using com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        roomId_ = 0L;

        messageId_ = 0L;

        status_ = 0;

        statusVersion_ = 0L;

        updaterAuthorHash_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.internal_static_proto_ChatUpdateStatusResponse_descriptor;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse getDefaultInstanceForType() {
        return com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse build() {
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse buildPartial() {
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse result = new com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.roomId_ = roomId_;
        result.messageId_ = messageId_;
        result.status_ = status_;
        result.statusVersion_ = statusVersion_;
        result.updaterAuthorHash_ = updaterAuthorHash_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse) {
          return mergeFrom((com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse other) {
        if (other == com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.getStatusVersion() != 0L) {
          setStatusVersion(other.getStatusVersion());
        }
        if (!other.getUpdaterAuthorHash().isEmpty()) {
          updaterAuthorHash_ = other.updaterAuthorHash_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.kianiranian.proto.ProtoResponse.Response response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>.proto.Response response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       * @return The response.
       */
      public com.kianiranian.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder setResponse(
          com.kianiranian.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder mergeResponse(com.kianiranian.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              com.kianiranian.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.Response.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      public com.kianiranian.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.kianiranian.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kianiranian.proto.ProtoResponse.Response, com.kianiranian.proto.ProtoResponse.Response.Builder, com.kianiranian.proto.ProtoResponse.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private long roomId_ ;
      /**
       * <code>uint64 room_id = 2;</code>
       * @return The roomId.
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 room_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private long messageId_ ;
      /**
       * <code>uint64 message_id = 3;</code>
       * @return The messageId.
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>uint64 message_id = 3;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 message_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @return The enum numeric value on the wire for status.
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @return The status.
       */
      public com.kianiranian.proto.ProtoGlobal.RoomMessageStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.kianiranian.proto.ProtoGlobal.RoomMessageStatus result = com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.valueOf(status_);
        return result == null ? com.kianiranian.proto.ProtoGlobal.RoomMessageStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.kianiranian.proto.ProtoGlobal.RoomMessageStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RoomMessageStatus status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private long statusVersion_ ;
      /**
       * <code>uint64 status_version = 5;</code>
       * @return The statusVersion.
       */
      public long getStatusVersion() {
        return statusVersion_;
      }
      /**
       * <code>uint64 status_version = 5;</code>
       * @param value The statusVersion to set.
       * @return This builder for chaining.
       */
      public Builder setStatusVersion(long value) {
        
        statusVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 status_version = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusVersion() {
        
        statusVersion_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object updaterAuthorHash_ = "";
      /**
       * <code>string updater_author_hash = 6;</code>
       * @return The updaterAuthorHash.
       */
      public java.lang.String getUpdaterAuthorHash() {
        java.lang.Object ref = updaterAuthorHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updaterAuthorHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string updater_author_hash = 6;</code>
       * @return The bytes for updaterAuthorHash.
       */
      public com.google.protobuf.ByteString
          getUpdaterAuthorHashBytes() {
        java.lang.Object ref = updaterAuthorHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updaterAuthorHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string updater_author_hash = 6;</code>
       * @param value The updaterAuthorHash to set.
       * @return This builder for chaining.
       */
      public Builder setUpdaterAuthorHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updaterAuthorHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string updater_author_hash = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdaterAuthorHash() {
        
        updaterAuthorHash_ = getDefaultInstance().getUpdaterAuthorHash();
        onChanged();
        return this;
      }
      /**
       * <code>string updater_author_hash = 6;</code>
       * @param value The bytes for updaterAuthorHash to set.
       * @return This builder for chaining.
       */
      public Builder setUpdaterAuthorHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updaterAuthorHash_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ChatUpdateStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ChatUpdateStatusResponse)
    private static final com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse();
    }

    public static com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatUpdateStatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChatUpdateStatusResponse>() {
      @java.lang.Override
      public ChatUpdateStatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatUpdateStatusResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatUpdateStatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatUpdateStatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kianiranian.proto.ProtoChatUpdateStatus.ChatUpdateStatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChatUpdateStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChatUpdateStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChatUpdateStatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChatUpdateStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ChatUpdateStatus.proto\022\005proto\032\rRequest" +
      ".proto\032\016Response.proto\032\014Global.proto\"\202\001\n" +
      "\020ChatUpdateStatus\022\037\n\007request\030\001 \001(\0132\016.pro" +
      "to.Request\022\017\n\007room_id\030\002 \001(\004\022\022\n\nmessage_i" +
      "d\030\003 \001(\004\022(\n\006status\030\004 \001(\0162\030.proto.RoomMess" +
      "ageStatus\"\301\001\n\030ChatUpdateStatusResponse\022!" +
      "\n\010response\030\001 \001(\0132\017.proto.Response\022\017\n\007roo" +
      "m_id\030\002 \001(\004\022\022\n\nmessage_id\030\003 \001(\004\022(\n\006status" +
      "\030\004 \001(\0162\030.proto.RoomMessageStatus\022\026\n\016stat" +
      "us_version\030\005 \001(\004\022\033\n\023updater_author_hash\030" +
      "\006 \001(\tB.\n\025com.kianiranian.protoB\025ProtoCha" +
      "tUpdateStatusb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kianiranian.proto.ProtoRequest.getDescriptor(),
          com.kianiranian.proto.ProtoResponse.getDescriptor(),
          com.kianiranian.proto.ProtoGlobal.getDescriptor(),
        });
    internal_static_proto_ChatUpdateStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ChatUpdateStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChatUpdateStatus_descriptor,
        new java.lang.String[] { "Request", "RoomId", "MessageId", "Status", });
    internal_static_proto_ChatUpdateStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ChatUpdateStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChatUpdateStatusResponse_descriptor,
        new java.lang.String[] { "Response", "RoomId", "MessageId", "Status", "StatusVersion", "UpdaterAuthorHash", });
    com.kianiranian.proto.ProtoRequest.getDescriptor();
    com.kianiranian.proto.ProtoResponse.getDescriptor();
    com.kianiranian.proto.ProtoGlobal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
